### ISSUE TITLE
negative yearpublished causes exception

### ISSUE THREAD

**Issue by glawler** [lcosmin/boardgamegeek#19]
It looks like BGG is using unsigned ints for years. So when you search for Go, which has a published year of -2200, the API returns:

<yearpublished value="4294965096" />

That value gets cast to an "int" in api.py, which python happily converts to a long. Then the boardgamegeek library checks the type of yearpublished in search.py (line 27 or so), finds the value is a long and not an int, then throws an exception. 

This can be "fixed" in the boardgamegeek library by checking for a large year and converting to a negative int if found. Annoying and hacky but it should work. 

year = int(4294965096)
....
if year > 99999: # or something large
    year = int(-(pow(2, 32)-year))
...

**Comment by glawler** [comment]
BGG forum reference: http://boardgamegeek.com/article/21253888#21253888

**Comment by lcosmin** [comment]
Hmmm...let's hope they fix this issue; until then, yes, we'll have to work around it. I'll probably release a new version tomorrow.

**Comment by lcosmin** [comment]
ok, I released a fix, but applied it only to the years coming from the search results, for the moment.
