### ISSUE TITLE
SNIMissingWarning and InsecurePlatformWarning

### ISSUE THREAD

**Issue by gamesbook** [lcosmin/boardgamegeek#24]
I am running Python 2.7.6 - I get the following error when trying the example:

```
>>> g = bgg.game("Android: Netrunner")
/home/derek/.virtualenvs/boardgamegeek/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/home/derek/.virtualenvs/boardgamegeek/local/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

What do I need to do to overcome this?

**Comment by lcosmin** [comment]
Well, `requests`  tells you that some components are missing from your install and that you can get more info at https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning . 

Try updating your python version to a version later than 2.7.9 and upgrade `requests` to the latest version available.

**Comment by gamesbook** [comment]
Thanks.  I worked out how to use penv to create a virtualenv that has 2.7.9 .  This seems the best approach as upgrading the system Python on Ubuntu seems to be considered a "bad idea".

**Comment by vinitadpan** [comment]
Is there anyway to do this without upgrading to python 2.7.9? I am currently using python 2.7.6. Thanks

**Comment by lcosmin** [comment]
You can disable SSL by adding the `disable_ssl=True` parameter when creating an instance of `BoardGameGeek`, like so:

    bgg = BoardGameGeek(..., disable_ssl=True)

This should work around the issue.

**Comment by vinitadpan** [comment]
I have created a virtual environment as suggested and not upgraded the requests packages. But still facing the same issue. I am trying to run the below linux command from my virtual environment (which has python 2.7.9)

 sudo tox -e genopts

/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Exception:
Traceback (most recent call last):
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/commands/install.py", line 287, in run
    wheel_cache
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/basecommand.py", line 269, in populate_requirement_set
    session=session, wheel_cache=wheel_cache):
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/download.py", line 409, in get_file_content
    resp = session.get(url)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/download.py", line 378, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/cachecontrol/adapter.py", line 46, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/opt/stack/cinder/.tox/pep8/local/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed


Any help would be greatly appreciated!

**Comment by lcosmin** [comment]
For me, there's no warning produced on a Python 2.7.9 virtualenv, with the following installed:

    boardgamegeek==0.13.2
    requests==2.10.0
    requests-cache==0.4.12

But as I said in my comment, use `disable_ssl` and it will work without problems on Python 2.7.6 too.

**Comment by gamesbook** [comment]
`disable_ssl` works for me.
