### ISSUE TITLE
Game API does not include a min/max playing time property

### ISSUE THREAD

**Issue by commadelimited** [lcosmin/boardgamegeek#26]
When investigating the response from this library, the game Port Royal does not include a min/max playing time, but instead only includes the singular property `playing_time`. In the case of Port Royal, the `playing_time` property only includes the max playing time, and not the min.

Reference the [raw XML response](https://www.boardgamegeek.com/xmlapi2/thing?id=156009&stats=1) for additional details:

```
<playingtime value="50"/>
<minplaytime value="20"/>
<maxplaytime value="50"/>
```

This library does include min/max for player count, and min for age.

**Comment by commadelimited** [comment]
Actually it looks like you've already added `minplaytime` and `maxplaytime` in the `develop` branch:
https://github.com/commadelimited/boardgamegeek/blob/1c131b995d512b651a724ed37bbf06c03dfc4af0/boardgamegeek/api.py#L792

Do you know when you expect to release this to PyPi?

**Comment by lcosmin** [comment]
No, unfortunately I don't have a release date, as I get to work on the project only sporadically. 
Could installing from Github directly help you in the mean while? 

    pip install git+https://github.com/lcosmin/boardgamegeek.git@develop

**Comment by commadelimited** [comment]
Yep. That'd totally do it. I actually installed from my copy where I made the change. But that was an older version of the lib. I'll switch to yours.

**Comment by lcosmin** [comment]
Ok, I've released the new version as boardgamegeek2 ( https://pypi.python.org/pypi/boardgamegeek2/0.0.1 ), so I'm going to close this issue for now. Sorry for the delay 👼
