### ISSUE TITLE
Make tests true unit tests

### ISSUE THREAD

**Issue by pak21** [lcosmin/boardgamegeek#35]
What would your thoughts be on making the tests true unit tests (i.e. ones which don't depend on any external systems)? For example, changing `test_get_unknown_game_info` in `test_game.py` to something like:

    class MockResponse():
        def __init__(self, text):
            self.headers = {'content-type': 'text/xml'}
            self.status_code = 200
            self.text = text

    def test_get_unknown_game_info(bgg, mocker):
        mock_get = mocker.patch('requests.sessions.Session.get')
        mock_get.return_value = MockResponse('<?xml version="1.0" encoding="utf-8"?><items total="0" termsofuse="http://boardgamegeek.com/xmlapi/termsofuse"></items>')

        with pytest.raises(BGGItemNotFoundError):
            game = bgg.game(TEST_INVALID_GAME_NAME)
The advantages of this would be twofold:

1. Remove the dependency on the specific text being returned by BGG (as we're mocking it out) - therefore the tests would no longer start failing every time someone adds a new mechanic to Agricola or similar changes.
2. Make the tests run *much* quicker - no network access, and no need to add that 15 second throttle to avoid BGG getting grumpy with us.

**Comment by lcosmin** [comment]
Yes, it's a good idea! I had it on the todo list for a while now (but... 🙄 ); would you like to give the implementation a shot?

**Comment by pak21** [comment]
Sure, I'll give it a go in the next few days.

**Comment by pak21** [comment]
OK, I've committed a first stab at this in the [feature/true-unit-tests](https://github.com/pak21/boardgamegeek/tree/feature/true-unit-tests) branch in my fork - let me know what you think of the approach, and I'll work on the other tests. Just look at test_game.py and _common.py - the XML files are just the canned data we feed back.

**Comment by lcosmin** [comment]
Looks similar to what I had in mind 👍  

I think the .xml files with the raw data should be placed in a separated directory inside `test/` and they should be named like `test_name.test_id`, e.g. `test_get_unknown_game_info.1` for the response needed for the first api call in `test_get_unknown_game_info`.  IMO, this would make it easier to know which file belongs to which test (would also be nice if there's a comment in the unit test about how to get the raw data from BGG XML2 api , using curl for instance). 

I also tried a different way of mocking (should work, haven't tested much) which looks a bit simpler to me (but your way is ok too):

```
def mock_requests(test_name, test_id, status_code=200):

    r = mock.Mock()
    r.status_code = status_code
    r.headers.get.return_value = "text/xml"

    with open(os.path.join(os.path.dirname(__file__), "api_results", "{}.{}".format(test_name, test_id))) as f:
        r.text = f.read()

    m = mock.Mock()
    m.get.return_value = r
    return m

... 

def test_get_unknown_game_info(bgg):
    bgg.requests_session = mock_requests("test_get_unknown_game_info", 1)

    with pytest.raises(BGGItemNotFoundError):
        game = bgg.game(TEST_INVALID_GAME_NAME)

```

**Comment by pak21** [comment]
I finished off mocking out the rest of the tests earlier; I reworked the raw data handling a couple of times while going through it, but it's ended up in its own directory anyway. I've currently got the files named as exactly what the request is, which has some advantages, perhaps the primary one being its easy to see exactly which call is being made for each file. (Getting the files in this case is very easy as `wget` does the right thing out of the box). I can see the advantages of having the files named after the test as well though... happy to go with either.
I couldn't work out how to get `test_rate_limiting_for_requests` to work with the mocking, so that's still actually hitting the Internet.

**Comment by lcosmin** [comment]
Ok. If you think it's ready, send a pull request, please 🙂
Leave `test_rate_limiting_for_requests` as is for the moment; I guess it could be moved to a different test file, one which really uses the API (no mocks) and which is not picked up when unit tests are executed.
