### ISSUE TITLE
Docs: player_suggestions should be suggested_numplayers?

### ISSUE THREAD

**Issue by EmilStenstrom** [lcosmin/boardgamegeek#44]
Hi! Thanks for a great library. The BoardGame class has, according to the docs, a player_suggestions property. But I get KeyError trying to access it. I do get info back with the name suggested_numplayers, could that have changed, without the docs being updated?

**Comment by lcosmin** [comment]
Hmm, this is weird, for what game are you getting a `KeyError` ?  Can you provide some code? 

Using the object from your other issue:

```
>>> game.player_suggestions
[<boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25cd0>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25d10>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25d50>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25d90>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25dd0>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25e10>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25e50>, <boardgamegeek.objects.games.PlayerSuggestion object at 0x108a25e90>]
```

It also shouldn't work with `.suggested_numplayers` ...

**Comment by EmilStenstrom** [comment]
That is really strange, do I have another version of the library?

```
>>> client = BGGClient()
>>> game = client.game(game_id=68448)
>>> game
BoardGame (id: 68448)
>>> game.player_suggestions
Traceback (most recent call last):
  File "/Users/EmilStenstrom/Envs/mybgg/lib/python3.6/site-packages/boardgamegeek/utils.py", line 98, in __getattr__
    return self._data[item]
KeyError: 'player_suggestions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/EmilStenstrom/Envs/mybgg/lib/python3.6/site-packages/boardgamegeek/utils.py", line 100, in __getattr__
    raise AttributeError
AttributeError
```

Wait a minute. I should be using https://pypi.org/project/boardgamegeek2/ right? Version 0.0.1?

**Comment by lcosmin** [comment]
Yeah, you need to use boardgamegeek2, but I don't think I've released this change to PyPI. 

Try to see if installing the package like this solves your issue: 
`pip install git+https://github.com/lcosmin/boardgamegeek.git@develop`

**Comment by lcosmin** [comment]
Pushed version 1.0.0rc2 to PyPI
