### ISSUE TITLE
Fix URLs / status codes in unit tests

### ISSUE THREAD

**Issue by arnauldvm** [lcosmin/boardgamegeek#56]
I had to do some investigation following the discussion in PR #55 and tested the actual HTTP codes for all the URLs simulated by the unit tests.

> The reason is that the implementation of the legacy api required to trap the status code 404,
> to detect item not found errors.
> We had to verify if this have impact on existing requests for the (non-legacy) API.

**Comment by arnauldvm** [comment]
This is the script I used:

```bash
#!/usr/bin/env bash

BASE_URL_XMLAPI=https://www.boardgamegeek.com/xmlapi
BASE_URL_XMLAPI2=https://www.boardgamegeek.com/xmlapi2

test_dir="$(dirname "$0")"

cd "$test_dir"/xml

delay=1
find . -type f -exec basename {} \; | while read path; do
  path="${path//\%25//}"
  path="${path// /+}"
  if [[ "$path" =~ ^geeklist/ ]]; then
    base_url="$BASE_URL_XMLAPI"
  else
    base_url="$BASE_URL_XMLAPI2"
  fi
  url="$base_url/$path"
  status_code=""
  while [ -z "$status_code" -o "$status_code" = "202" -o "$status_code" = "429" ]; do
    echo -n "."
    status_code=$(
      curl -s -o /dev/null -w "%{http_code}" "$url"
    )
    [ "$status_code" == "429" ] && delay=$((delay + 1))
    sleep $delay  # throttling to avoid 429 Too Many Requests
  done
  echo " $url -> $status_code"
done
```

**Comment by arnauldvm** [comment]
And the result of the test:

```shell
$ ./test/test_urls.sh | grep -v 200
. https://www.boardgamegeek.com/xmlapi/geeklist/-1 -> 404
```

**Comment by arnauldvm** [comment]
**Conclusion**

As far as the unit tests are concerned, I could not find any other request where BGG returns a 404.

Hence, the modification (about the code 404) brought by PR #55 should not have any impact on the existing code base.

**Comment by arnauldvm** [comment]
I don't know if it could be useful to push my script in the repo.

Else, you may close this ticket.

**Comment by lcosmin** [comment]
I forgot to comment on the pull request; I did some manual testing and it seems the xml api 2 doesn't return 404 when an item is not found, but an almost empty XML and HTTP 200.

I don't think it makes sense to commit your script to the repo, as this was an one time only test. We'll have it in this issue if it's going to be needed again.
