### ISSUE TITLE
Can't git clone on Windows because of '?' in file names

### ISSUE THREAD

**Issue by azezpz1** [lcosmin/boardgamegeek#58]
I was planning on cloning the repo on my Windows PC, but when I try to do so, I get several errors about being unable to create files in the test/xml directory. My guess is that it's because the filenames there have the '?' character in the name, which is apparently not allowed on Windows. Is there anyway to rename these files to allow development on Windows? I'm not sure what the repercussions of this would be, so I figured I'd post about it and ask.

Thanks!

**Comment by lcosmin** [comment]
Can you try now, using the `develop` branch?

**Comment by azezpz1** [comment]
That fixed it. Thanks!
